server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: http://auth-service:8080
          predicates:
            - Path= /auth/**
          filters:
            - RewritePath= /auth(?<segment>/?.*), $\{segment}
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path= /product/**
          filters:
            - RewritePath= /product(?<segment>/?.*), $\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path= /user/**
          filters:
            - RewritePath= /user(?<segment>/?.*), $\{segment}
        - id: promotion-service
          uri: http://promotion-service:8080
          predicates:
            - Path= /promotion/**
          filters:
            - RewritePath= /promotion(?<segment>/?.*), $\{segment}
        - id: search-product-service
          uri: http://search-product-service:8080
          predicates:
            - Path= /elastic/**
          filters:
            - RewritePath= /elastic(?<segment>/?.*), $\{segment}
        - id: email-service
          uri: http://email-service:8080
          predicates:
            - Path= /mail/**
          filters:
            - RewritePath= /mail(?<segment>/?.*), $\{segment}
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path= /order/**
          filters:
            - RewritePath= /order(?<segment>/?.*), $\{segment}
        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path= /payment/**
          filters:
            - RewritePath= /payment(?<segment>/?.*), $\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://auth.naybxrz.com/auth/realms/api-gateway}
          jwk-set-uri: ${JWK_SET_URI:https://auth.naybxrz.com/auth/realms/api-gateway/protocol/openid-connect/certs}
  sleuth:
    reactor:
      instrumentation-type: DECORATE_ON_LAST
    sampler:
      percentage: 1.0
      probability: 1.0
      opentracing:
        enabled: true     
  zipkin:
    baseUrl: http://jaeger:9411


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO
  config: classpath:logback-spring.xml
