server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path= /product/**
          filters:
            - RewritePath= /product(?<segment>/?.*), $\{segment}
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path= /user/**
          filters:
            - RewritePath= /user(?<segment>/?.*), $\{segment}
        - id: promotion-service
          uri: http://promotion-service:8080
          predicates:
            - Path= /promotion/**
          filters:
            - RewritePath= /promotion(?<segment>/?.*), $\{segment}
        - id: search-product-service
          uri: http://search-product-service:8080
          predicates:
            - Path= /elastic/**
          filters:
            - RewritePath= /elastic(?<segment>/?.*), $\{segment}
        - id: email-service
          uri: http://email-service:8080
          predicates:
            - Path= /mail/**
          filters:
            - RewritePath= /mail(?<segment>/?.*), $\{segment}
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path= /order/**
          filters:
            - RewritePath= /order(?<segment>/?.*), $\{segment}
        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path= /payment/**
          filters:
            - RewritePath= /payment(?<segment>/?.*), $\{segment}
        - id: authentication-service
          uri: http://authentication-service:8080
          predicates:
            - Path= /authentication/**
          filters:
            - RewritePath= /authentication(?<segment>/?.*), $\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  security:
    oauth2:
#      client:
#        registration:
#          api-gateway:
#            provider: keycloak
#            client-id: api-gateway-client
#            client-secret: 05807f3c-7d3d-4c4a-ade4-2db7f70abc51
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            #redirect-uri: "http://localhost:9191/authorize/oauth2/code/{registrationId}"
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/auth/realms/api-gateway
            #http://localhost:8080/auth/realms/api-gateway
            #authorization-uri: http://localhost:8282/oauth/token
            #authorization-uri: http://localhost:8080/auth/realms/api-gateway/protocol/openid-connect/auth
            #token-uri: http://localhost:8282/oauth/token
            #token-uri: http://localhost:8080/auth/realms/api-gateway/protocol/openid-connect/token
            #user-info-uri: http://localhost:8282/resources/userinfo
            #user-info-uri: http://localhost:8080/auth/realms/api-gateway/protocol/openid-connect/userinfo
            #jwk-set-uri: http://localhost:8080/auth/realms/api-gateway/protocol/openid-connect/certs
            #user-name-attribute: preferred_username
#
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://192.168.64.4:30080/auth/realms/api-gateway}
          jwk-set-uri: ${JWK_SET_URI:http://192.168.64.4:30080/auth/realms/api-gateway/protocol/openid-connect/certs}
      
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: INFO
