server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  sendgrid: 
    api-key: '{cipher}AQBdiXumdv4dl1+JczDxrPjyOuc6sUHiXy/dOVtcwdKww9D8gqzxkKowh9eS6RYvpUYgKT14NOt1ZLATkcKb6KrhshqhBFINcyEyiafg7k6Dm1coprJSyz3MwP6D5VxTyGXTPVGYK+57jYw7SENbHGD5y/1Uxl1MpNqEgCatj2wsCoGQ0/AqbhEgGLonYKMwUctYymzhNMBkse2UQvcUQsG8lwxsXRWh41VyQSw915zXqRlk1gHsq3VjelR96GkhFitbMfWLUcFeN/YHiNV+WYv2cJrhIlQUrjRMQwB75NpYca+5RXuD21PZ4rdtnItwYtLyQC7/URn3osTvK3J5gzyKcxAB2Oc+D9hqE1fD91kiVlbhcgqHFcHyK1zn5rv/W8HMaLZ2uweJ1IND+X6CeZ6yPLK+AWkSLXGkPSJy13f8X27TyZdutkLvSIW9Pe4/rUq/SbMhseXk3rtCgxPfvBum'
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    sender:
      type: web
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

sendGrid:
  mail:
    from: '{cipher}AQCHkD6OUvyvrcFmDR0XX7oSj9G4ZyXAt7+stFamP2rMtapgZjzT0UAU1ZDZNYPMdt2LV/+55q29YSqWMNEAomZrjItx1oeAbQ6oXBgkZW4f6YagjDdE6B0iwODkAoNP1xKAlyR/nbGgTmnGglLP+DmaKJsplkfpKO4H84rxouM+mnjfDkIJc+5JeDDAkxkRjoNfP4EF742VVlAYfjJuowZEsV1V1+vhRGucsPfpsWWpZkDCNffajB7gCtYqtBdQXZeW5x537uOVVM6FisemeS6PwO0274B44d+o5BB0ywO4D9bcvQHZbIOAI2y7Qxd3Vqe2+TgUoCgMHBGSkX3KUp1YaDdgl7GkNaPt5LGNBbVNl0jgFybkDaBjutTa+MGylOXgCU6KA8VTYfNEyaWcJSkO'
    templateConfirmationId: d-16c5a50505b845ceba96425e30fbc196
    templatePendingId: d-842d74a4b0d14881b640f5bac1899e2b
    templateRefusedId: d-c2136dc4841949c9b0aa69b871fed307
    templateContact: d-3501983e85884ab29135f6d2d2527625
    templateSubscriptionId: d-45d928c780ac40bc9c534497e1f63f21


kafka:
  bootstrapAddress: ${KAFKA_SERVER:localhost:9092}
  groupId: ordersGroup
  topic: orders
