server:
  port: 9090

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    product:
      path: /product/**
      serviceId: product-service
    category:
      path: /category/**
      serviceId: category-service
    user:
      path: /user/**
      serviceId: user-service

hystrix:
  command:
    user-service:
      execution:
        timeout:
          enabled: false
      isolation:
        thread:
          timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 6000000
  ReadTimeout: 6000000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  metadataMap:
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}AQAZms+f2Lq4wLcMnZMStTcVqBUCFyDU1GaLdFrOnxx7IkDkxxrxVB5loD6akcAQIy3dbzX0tEUf5kO/mWO66xjH9pWxRtGQdnSfeVVBVaYe5n8r7v6T6Vf5DD2RCtdnY5ROMLenTiwry6t/zylKsYWZs4xADj2yd5RCEpGdVIdS4p070UAuDY8H4om1bH94afsek6TE5e074Ns4mjBxubRSJbRANIbV1APpYOjmMQGylDbZaKm7CHCb3qBuO9JLX7ITht7x+ouIq92nKYsfMHjBH1trgT3k4JtUcxQnmiWvzC+lb89DH3k1mn45Eg11tqx0tWdJMo6pV8JTzF8tRokgdjzfXI0RmEzLDbGoYcC7JtuDUHEDnnwBHwVWFmG2cRE='

management:
  endpoints:
    web:
      exposure:
        include: "*"
