server:
  port: 8086


management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orders
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max-in-flight-requests-per-connection: 1
        transaction-timeout-ms: 1000
        request-timeout-ms: 1000
        retry-backoff-ms: 1000
        
kafka:
  bootstrapAddress: localhost:9092
  consumer:
    topic: orders
    groupId: paymentGroup
  producer:
    topic: catchup-orders

stripe:
 url: https://api.stripe.com/v1/payment_methods
 public-key: pk_test_51HYJubArLuFLaKsZOhdxmDtK9maKASFBIz3psXPKxQCRKYOht7IlxTuY2He3wyxlvO3vzMsBHpawyr5KXi5h4xXw00DExv250F
