server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  sleuth:
    reactor:
      instrumentation-type: manual
    sampler:
      percentage: 1.0
      probability: 1.0
  zipkin:
    baseUrl: http://jaeger-collector:9411
  
kafka:
  bootstrapAddress: kafka-cluster-kafka-bootstrap.production.svc:9092
  consumer:
    topic: orders
    groupId: paymentGroup
  producer:
    topic: catchup-orders

stripe:
 url: https://api.stripe.com
 public-key: pk_live_51HYJubArLuFLaKsZkd5OIrXuIWVbtjzMxqGlgCDCvWfcrt3yyhxHGQJratyUqyVBad4ySc80Fkm2uNiX8djLurqe00VTuFsOUQ

order:
 url: http://order-service:8080
 redirect: https://naybxrz.com/processing
