server:
  port: 8087
  
management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
      
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orders
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max-in-flight-requests-per-connection: 1
        transaction-timeout-ms: 1000
        request-timeout-ms: 1000
        retry-backoff-ms: 1000
  sleuth:
    reactor:
      instrumentation-type: manual
    sampler:
      percentage: 1.0
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411
  
  
kafka:
  bootstrapAddress: localhost:9092
  consumer:
    topic: orders
    groupId: paymentGroup
  producer:
    topic: catchup-orders

stripe:
 url: https://api.stripe.com
 public-key: pk_live_51HYJubArLuFLaKsZkd5OIrXuIWVbtjzMxqGlgCDCvWfcrt3yyhxHGQJratyUqyVBad4ySc80Fkm2uNiX8djLurqe00VTuFsOUQ
 #sk_test_51HYJubArLuFLaKsZh7FrusGK6heQuk5nXZMBUQTjKvOX1X2eQWmBa2r3b2Y1DoW1gZ1gySQqmhulgEPKL8iS4b0900FjjO3TLL

order:
 url: http://localhost:8086
 redirect: http://localhost:3000/processing
