server:
  port: 8086


management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: orders
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max-in-flight-requests-per-connection: 1
        transaction-timeout-ms: 1000
        request-timeout-ms: 1000
        retry-backoff-ms: 1000
        
kafka:
  bootstrapAddress: localhost:9092
  consumer:
    topic: orders
    groupId: paymentGroup
  producer:
    topic: catchup-orders

stripe:
 url: https://api.stripe.com
 public-key: sk_test_51HYJubArLuFLaKsZh7FrusGK6heQuk5nXZMBUQTjKvOX1X2eQWmBa2r3b2Y1DoW1gZ1gySQqmhulgEPKL8iS4b0900FjjO3TLL
