server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  metadataMap:
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    registryFetchIntervalSeconds: 30

spring:
  rabbitmq:
    host: ${RABBITMQ_SERVER:localhost}
    port: 5672
    username: guest
    password: '{cipher}AQAZms+f2Lq4wLcMnZMStTcVqBUCFyDU1GaLdFrOnxx7IkDkxxrxVB5loD6akcAQIy3dbzX0tEUf5kO/mWO66xjH9pWxRtGQdnSfeVVBVaYe5n8r7v6T6Vf5DD2RCtdnY5ROMLenTiwry6t/zylKsYWZs4xADj2yd5RCEpGdVIdS4p070UAuDY8H4om1bH94afsek6TE5e074Ns4mjBxubRSJbRANIbV1APpYOjmMQGylDbZaKm7CHCb3qBuO9JLX7ITht7x+ouIq92nKYsfMHjBH1trgT3k4JtUcxQnmiWvzC+lb89DH3k1mn45Eg11tqx0tWdJMo6pV8JTzF8tRokgdjzfXI0RmEzLDbGoYcC7JtuDUHEDnnwBHwVWFmG2cRE='
  data:
    mongodb:
      host: ${MONGO_SERVER:mongo} #localhost
      port: 27017 #27018
      database: products
      #uri: mongodb://localhost/products
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    sender:
      type: web
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
      client-id: productId
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx.
      properties:
        max-in-flight-requests-per-connection: 1
        transaction-timeout-ms: 1000
        request-timeout-ms: 1000
        retry-backoff-ms: 1000
    consumer:
      bootstrap-servers: ${KAFKA_SERVER:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  topic: products

security:
  active: true
  
fallback:
  products:
    men:
      id: 12345,56789
      name: Sweat Crew II,Shirt Retro
      brand: Nike,Carhartt
      price: 70,30
      size: M,S
      colors: Black,White
      logo: https://www.festisite.com/static/partylogo/img/logos/nike.png,https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Carhartt_logo.svg/1200px-Carhartt_logo.svg.png
      images: https://images.asos-media.com/products/nike-logo-crew-sweat-in-white-804340-100/7134528-3?$XXL$&wid=513&fit=constrain,https://cdn-images.farfetch-contents.com/13/56/66/14/13566614_16285570_1000.jpg      
    women:
      id: 9876,4321
      name: Classic Girl Bomber,Top 90's
      brand: Carhartt,Obey
      price: 80,40
      size: S,S
      colors: Black,White
      logo: https://1000logos.net/wp-content/uploads/2017/07/Obey-Logo.png,https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Carhartt_logo.svg/1200px-Carhartt_logo.svg.png
      images: https://i1.adis.ws/i/carhartt_wip/I025115_05V_90-ST-01/w-deming-jacket-panther-print-blast-red-black-black-1739.png?$pdp_zoom$,https://image.s5a.com/is/image/TheBay/193259181863_main?wid=984&hei=1312&qlt=90&resMode=sharp2&op_usm=0.9,1.0,8,0    


