server:
  port: 8080
  
spring:
  sleuth:
    reactor:
      instrumentation-type: DECORATE_ON_LAST
      
management:
  endpoints:
    health:
      show-details: always
      probes:
        enabled: true
    web:
      exposure:
        include: "*"
        
kafka:
  bootstrapAddress: ${KAFKA_SERVER:kafka-cluster-kafka-bootstrap.production.svc:9092}
  groupId: indexedOrders
  topic: orders

elasticsearch:
  index: store_orders
  server: ${ELASTICSEARCH_SERVER:elasticsearch:9200}
