server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
   sleuth:
    #reactor:
    #  instrumentation-type: manual
    sampler:
      percentage: 1.0
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411


kafka:
  bootstrapAddress: ${KAFKA_SERVER:localhost:9092}
  groupId: products
  topic: products

elasticsearch:
  index: store_products
  server: ${ELASTICSEARCH_SERVER:localhost:9200}
