server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    sender:
      type: web

kafka:
  bootstrapAddress: ${KAFKA_SERVER:localhost:9092}
  groupId: indexedOrders
  topic: orders

elasticsearch:
  index: store_orders
  server: ${ELASTICSEARCH_SERVER:localhost:9200}
