server:
  port: 8080

management:
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    elasticsearch:
      enabled: true
spring:
  sleuth:
    reactor:
      instrumentation-type: manual
    sampler:
      percentage: 1.0
      probability: 1.0
  zipkin:
    baseUrl: http://jaeger-collector.default.svc:9411


kafka:
  bootstrapAddress: ${KAFKA_SERVER:kafka-cluster-kafka-bootstrap.production.svc:9092}
  groupId: products
  topic: products

elasticsearch:
  index: store_products
  server: ${ELASTICSEARCH_SERVER:elasticsearch-master.production.svc:9200}
