server:
  port: 8080

management:
  endpoints:
    health:
      show-details: always
      probes:
        enabled: true
    web:
      exposure:
        include: "*"
spring:
  sleuth:
    reactor:
      instrumentation-type: manual
    sampler:
      percentage: 1.0
      probability: 1.0
  zipkin:
    baseUrl: http://jaeger:9411


kafka:
  bootstrapAddress: ${KAFKA_SERVER:kafka-cluster-kafka-bootstrap.production.svc:9092}
  groupId: products
  topic: products

elasticsearch:
  index: store_products
  server: ${ELASTICSEARCH_SERVER:elasticsearch:9200}
