server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
    #cluster:
    # nodes: localhost:6379
  session:
    redis:
      flush-mode: IMMEDIATE
  sleuth:
    reactor:
      instrumentation-type: manual
    redis:
      enabled: true
    sampler:
      percentage: 1.0
      probability: 1.0
    opentracing:
        enabled: true
  zipkin:
    baseUrl: http://localhost:9411
    
kafka:
  bootstrapAddress: ${KAFKA_SERVER:localhost:9092}
  producer:
    topic: users
 
      
management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    
