server:
  port: 8083
spring:
  redis:
    host: localhost
    port: 6379
    #cluster:
    # nodes: localhost:6379
  session:
    redis:
      flush-mode: IMMEDIATE
  sleuth:
    sampler:
      percentage: 1.0
      probability: 1.0
    opentracing:
        enabled: true
    traceId128: true
  zipkin:
    baseUrl: http://localhost:9411
 
      
management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    
