server:
  port: 8080
spring:
  redis:
    host: redis-master.production.svc.cluster.local
    port: 6379
    password: P455w0rd!!
  session:
    redis:
      flush-mode: IMMEDIATE
  sleuth:
    reactor:
      instrumentation-type: manual
    redis:
      enabled: true
    sampler:
      percentage: 1.0
      probability: 1.0
    opentracing:
        enabled: true
  zipkin:
    baseUrl: http://jaeger-collector:9411
    
kafka:
  bootstrapAddress: ${KAFKA_SERVER:kafka-cluster-kafka-bootstrap.production.svc:9092}
  producer:
    topic: users
      
management:
  endpoint:
    web:
      exposure:
        include: "*"   
    health:
      show-details: always
      probes:
        enabled: true
  health:
    redis:
      enabled: true
    
