server:
  port: 8083
spring:
  redis:
    host: localhost
    port: 6379
    #cluster:
    # nodes: localhost:6379
  session:
    redis:
      flush-mode: IMMEDIATE
      
management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    
